#'
#' Error handling for non-200 status codes
#' @param response Response generated by a request such as \code{httr::GET()}
#' or \code{httr::POST()}
check_status <- function(response) {
  status <- httr::status_code(response)

  if(status != "200") {
    content <- httr::content(response)
    if("message" %in% names(content)) {
      stop(paste(status, content$exceptionName, content$message))
      return(response)
    } else {
      stop(paste(status, "Unexpected Response"))
      return(response)
    }
  }

  return(response)
}


#' Build Request URL
#'
#' This provides a manual way to build a request URL but in general this
#' should be handled by the specific endpoint functions
#' @param gallery URL for your Alteryx Gallery
#' @param endpoint The api endpoint beginning and ending with "/"
#' @param request_method HTTP request verb
#' @param request_params List of request parameters
#' @export
build_request_url <- function(gallery,
                              endpoint,
                              request_method,
                              request_params) {
  required_headers <- generate_required_headers()
  oauth_signature <- build_signature(gallery,
                                     endpoint,
                                     request_method,
                                     required_headers,
                                     request_params)
  params <- append(required_headers, request_params)
  params <- append(params, list(oauth_signature = oauth_signature))
  params <- params[sort(names(params))]
  params <- paste0(names(params), "=", params, collapse = "&")
  request_url <- paste0(gallery, endpoint, "?", params)

  return(request_url)
}

#' Remove Byte Order Mark
#'
#' Janky way to remove BOM from response content
#' @param content Content from response generated by \code{httr::content()}
remove_bom <- function(content) {
  #a janky way for now to deal with BOM
  t <- tempfile()
  jsonlite::write_json(content, t)
  content <- jsonlite::read_json(t)[[1]]
  content <- gsub("<U\\+FEFF>", "", content)

  return(content)
}

#' Submit GET Request
#'
#' This provides a manual way to submit a GET request but in general this
#' should be handled by the specific endpoint functions
#' @inheritParams build_request_url
#' @param ... Additional arguments passed to \code{httr::GET()} such as
#' \code{verbose()}
#' @export
submit_get_request <- function(gallery,
                               endpoint,
                               request_params,
                               ...) {
  request_method <- "GET"
  request_url <-
    build_request_url(gallery,
                      endpoint,
                      request_method,
                      request_params)
  response <- httr::GET(request_url)
  content <- parse_request_response(response, ...)

  return(content)
}

parse_request_response <- function(response,
                                   as = "text",
                                   remove_bom = TRUE,
                                   parse_JSON = TRUE) {
  response <- check_status(response)
  content <- httr::content(response, as = as, encoding = "UTF-8")

  if(remove_bom)
    content <- remove_bom(content)
  if(parse_JSON)
    content <- jsonlite::fromJSON(content, simplifyVector = FALSE)

  return(content)
}

#' Submit POST Request
#'
#' This provides a manual way to submit a POST request but in general this
#' should be handled by the specific endpoint functions
#' @inheritParams build_request_url
#' @param request_body JSON body of request containing values for app questions
#' built using \code{build_request_body}
#' @param ... Additional arguments passed to \code{httr::POST()} such as
#' \code{verbose}
submit_post_request <- function(gallery,
                                endpoint,
                                request_params,
                                request_body,
                                ...) {
  request_method <- "POST"
  request_url <-
    build_request_url(gallery,
                      endpoint,
                      request_method,
                      request_params)
  response <- httr::POST(request_url,
                         body = request_body,
                         encode = "raw",
                         httr::content_type_json())
  content <- parse_request_response(response, ...)

  return(content)
}

#' Build Request Body
#'
#' Build the JSON of name value pairs corresponding to app questions for
#' @param name_value \code{list} containing an app question \code{name} and
#' \code{value} pair
#' @param ... Additional \code{name_value} pairs
#' @export
#' @examples
#' first_question <- list(name = "a", value = "1")
#' second_question <- list(name = "b", value = "2")
#' build_request_body(first_question, second_question)
build_request_body <- function(name_value, ...) {
  questions <- list(name_value, ...)
  jsonlite::toJSON(list(questions = questions), auto_unbox = TRUE)
}
