#' URL Encode List
#'
#' URL encode all values in a list using \code{utils::URLencode()}
#' @param l a list
#' @param reserved logical: should ‘reserved’ characters be encoded?
encode_list <- function(l, reserved = TRUE) {
  lapply(l, function(x) {
    utils::URLencode(x, reserved = reserved)
  })
}

#' Status Code Check
#'
#' Error handling for non-200 status codes
#' @param response Response generated by \code{httr::GET()}
check_status <- function(response) {
  status <- httr::status_code(response)

  if(status != '200') {
    content <- httr::content(response)
    if("message" %in% names(content)) {
      stop(paste(status, content$exceptionName, content$message))
      return(response)
    } else {
      stop(paste(status, "Unexpected Response"))
      return(response)
    }
  }

  return(response)
}
